// Supabase Edge Function: catalogue-admin
//
// Publishes the word catalogue over the air, so a content change reaches
// installed apps without a store release. Not on any user-facing path — the
// app itself never calls this. It reads the published files straight off the
// public CDN (see CatalogueOta in the Flutter client); this function only
// exists to WRITE them.
//
// Why a function at all, rather than uploading with the service-role key from
// a laptop or from CI: the service-role key bypasses every RLS policy in the
// project. It already lives here (the `tts` and `explain` functions need it),
// so keeping it here and handing out narrowly-scoped signed upload URLs adds
// no new place for it to leak from. tools/publish_catalogue.py holds only the
// admin token below, which grants exactly this: write to one storage bucket.
//
// SECURITY. Fails closed, same as dict-setup: with no CATALOGUE_ADMIN_TOKEN
// set, every request is refused. Set one before first use —
//
//     supabase secrets set CATALOGUE_ADMIN_TOKEN="$(openssl rand -hex 32)"
//
// and never reuse DICT_ADMIN_TOKEN for it. They guard different blast radii
// (one can rewrite pronunciations for every user; this one can rewrite the
// word list for every user) and sharing a secret between them means a leak of
// either is a leak of both.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ADMIN_TOKEN = Deno.env.get("CATALOGUE_ADMIN_TOKEN") ?? "";

const BUCKET = "catalogue";

// Payload names are generated by the publisher, but this function is the last
// thing between a typo and a file written somewhere unintended.
const PATH_RE = /^words-g[0-9]{1,9}\.json\.gz$/;

function cors() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers":
      "authorization, x-client-info, apikey, content-type, x-admin-token",
  };
}

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...cors(), "Content-Type": "application/json" },
  });
}

/** Constant-time compare, so the gate can't be probed a character at a time. */
function tokenMatches(supplied: string | null): boolean {
  if (!ADMIN_TOKEN) return false;
  if (!supplied) return false;
  const a = new TextEncoder().encode(supplied);
  const b = new TextEncoder().encode(ADMIN_TOKEN);
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

/** Validates a manifest to the same rules CatalogueManifest.tryParse applies.
 *
 * Duplicated on purpose. The client checks because it must never trust the
 * network; this checks because a manifest that the client silently rejects is
 * indistinguishable, from the publisher's side, from one that was never
 * published — and that is a bad afternoon. Failing loudly here turns it into
 * an error message.
 */
function validateManifest(m: unknown): string | null {
  if (typeof m !== "object" || m === null) return "manifest must be an object";
  const o = m as Record<string, unknown>;
  if (o.schema !== 1) return "schema must be 1";
  if (typeof o.generation !== "number" || !Number.isInteger(o.generation) ||
      o.generation < 1) {
    return "generation must be a positive integer";
  }
  if (o.minAppBuild !== undefined &&
      (typeof o.minAppBuild !== "number" || !Number.isInteger(o.minAppBuild) ||
       o.minAppBuild < 0)) {
    return "minAppBuild must be a non-negative integer";
  }
  if (typeof o.path !== "string" || !PATH_RE.test(o.path)) {
    return "path must look like words-g<n>.json.gz";
  }
  if (typeof o.bytes !== "number" || !Number.isInteger(o.bytes) ||
      o.bytes <= 0 || o.bytes > 96 * 1024 * 1024) {
    return "bytes must be a positive integer under 96MB";
  }
  if (typeof o.sha256 !== "string" || !/^[0-9a-f]{64}$/.test(o.sha256)) {
    return "sha256 must be 64 lowercase hex characters";
  }
  if (o.disabled !== undefined && typeof o.disabled !== "boolean") {
    return "disabled must be a boolean";
  }
  return null;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors() });
  try {
    if (!tokenMatches(req.headers.get("x-admin-token"))) {
      if (!ADMIN_TOKEN) {
        console.warn("catalogue-admin called but CATALOGUE_ADMIN_TOKEN is unset");
      }
      return json({ error: "forbidden" }, 403);
    }
    if (!SERVICE_ROLE_KEY) return json({ error: "not configured" }, 500);

    const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
    const storage = supabase.storage.from(BUCKET);

    let body: Record<string, unknown>;
    try {
      body = await req.json();
    } catch {
      return json({ error: "invalid JSON body" }, 400);
    }
    const action = body.action;

    // What is live right now: the manifest clients are reading, and what is
    // actually sitting in the bucket. Run before and after a publish.
    if (action === "status") {
      const { data: files, error: listErr } = await storage.list("", {
        limit: 100,
        sortBy: { column: "name", order: "asc" },
      });
      if (listErr) {
        console.error("list failed", listErr);
        return json({ error: "storage error" }, 502);
      }
      let manifest: unknown = null;
      const { data: blob } = await storage.download("manifest.json");
      if (blob) {
        try {
          manifest = JSON.parse(await blob.text());
        } catch {
          manifest = { error: "manifest is not valid JSON" };
        }
      }
      return json({
        manifest,
        files: (files ?? []).map((f) => ({
          name: f.name,
          size: (f.metadata as Record<string, unknown> | null)?.size ?? null,
          updated_at: f.updated_at,
        })),
      });
    }

    // Hand back a URL that can write exactly one object in this bucket and
    // nothing else. The 6MB payload then goes straight from the publisher to
    // storage, never through this function — an Edge Function is the wrong
    // place to buffer a multi-megabyte body.
    if (action === "sign_upload") {
      const path = body.path;
      if (typeof path !== "string" || !PATH_RE.test(path)) {
        return json({ error: "path must look like words-g<n>.json.gz" }, 400);
      }
      // upsert so re-publishing the same generation after a failed run works.
      // The generation still has to increase for clients to take it, so this
      // cannot quietly change what an installed app already has.
      const { data, error } = await storage.createSignedUploadUrl(path, {
        upsert: true,
      });
      if (error) {
        console.error("sign failed", error);
        return json({ error: "storage error" }, 502);
      }
      return json({ path, signedUrl: data.signedUrl, token: data.token });
    }

    // The commit step. Until this runs, the payload is sitting in the bucket
    // and no client has any reason to look at it; after it runs, every client
    // will find it on its next check. Deliberately the last, smallest,
    // most-reversible thing in the sequence.
    if (action === "set_manifest") {
      const manifest = body.manifest;
      const problem = validateManifest(manifest);
      if (problem) return json({ error: problem }, 400);

      const m = manifest as Record<string, unknown>;
      // Refuse to advertise a payload that is not there. Without this, a
      // half-finished publish points every installed app at a 404, and the
      // only symptom is that content pushes quietly stop arriving.
      const { data: probe, error: probeErr } = await storage.list("", {
        limit: 100,
        search: m.path as string,
      });
      if (probeErr) {
        console.error("probe failed", probeErr);
        return json({ error: "storage error" }, 502);
      }
      if (!probe?.some((f) => f.name === m.path)) {
        return json({ error: `payload ${m.path} is not in the bucket` }, 409);
      }

      const { error } = await storage.upload(
        "manifest.json",
        new Blob([JSON.stringify(m, null, 2)], { type: "application/json" }),
        {
          upsert: true,
          contentType: "application/json",
          // Short, because this is the file that carries a rollback. The
          // payloads are content-addressed by generation and never change, so
          // they are cached hard by the client's own "already installed"
          // check rather than by the CDN.
          cacheControl: "60",
        },
      );
      if (error) {
        console.error("manifest upload failed", error);
        return json({ error: "storage error" }, 502);
      }
      return json({ published: m });
    }

    // Rollback. Rewrites the live manifest with disabled:true, which tells
    // every client to delete its downloaded catalogue and go back to the word
    // list compiled into its binary. No new build, no new payload, no version
    // bump — and it takes effect within one check interval.
    if (action === "disable") {
      const { data: blob } = await storage.download("manifest.json");
      if (!blob) return json({ error: "no manifest published" }, 404);
      let m: Record<string, unknown>;
      try {
        m = JSON.parse(await blob.text());
      } catch {
        return json({ error: "manifest is not valid JSON" }, 409);
      }
      m.disabled = body.disabled === false ? false : true;
      const problem = validateManifest(m);
      if (problem) return json({ error: problem }, 409);
      const { error } = await storage.upload(
        "manifest.json",
        new Blob([JSON.stringify(m, null, 2)], { type: "application/json" }),
        { upsert: true, contentType: "application/json", cacheControl: "60" },
      );
      if (error) {
        console.error("manifest upload failed", error);
        return json({ error: "storage error" }, 502);
      }
      return json({ manifest: m });
    }

    // Housekeeping: drop payloads for generations nobody should be fetching.
    // Never removes the one the live manifest points at.
    if (action === "prune") {
      const { data: blob } = await storage.download("manifest.json");
      let live: string | null = null;
      if (blob) {
        try {
          live = (JSON.parse(await blob.text()) as Record<string, unknown>)
            .path as string;
        } catch { /* treat an unreadable manifest as "keep everything" */ }
      }
      if (!live) return json({ error: "no readable manifest; refusing" }, 409);
      const { data: files, error: listErr } = await storage.list("", {
        limit: 100,
      });
      if (listErr) {
        console.error("list failed", listErr);
        return json({ error: "storage error" }, 502);
      }
      const doomed = (files ?? [])
        .map((f) => f.name)
        .filter((n) => PATH_RE.test(n) && n !== live);
      if (doomed.length === 0) return json({ removed: [] });
      const { error } = await storage.remove(doomed);
      if (error) {
        console.error("remove failed", error);
        return json({ error: "storage error" }, 502);
      }
      return json({ removed: doomed, kept: live });
    }

    return json({ error: "unknown action" }, 400);
  } catch (e) {
    console.error("catalogue-admin failed", e);
    return json({ error: "catalogue-admin failed" }, 500);
  }
});
